version: '3.8'

services: 
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "PsicologiaWeb"
      MYSQL_ROOT_PASSWORD: "Up6AmZ52Nxm"
      MYSQL_USER: "DavidFelipeVasquezPardo"
      MYSQL_PASSWORD: "Sup3rG4m3r05054545"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app:
    container_name: BackendPsicologia
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ""
      OPENAI_API_KEY: ""
    volumes:
      - .:/app